CREATE DATABASE mydatabase;
DROP DATABASE mydatabase;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE
);

ALTER TABLE users ADD COLUMN age INT;
DROP TABLE users;